### ISSUE TITLE
Formatting the projects page

### ISSUE THREAD

**Issue by svntax** [csccsm/CSC-at-CSM#32]
I worked on making the projects page look nicer, and this is what I have so far.

![projects-page-2](https://cloud.githubusercontent.com/assets/5898368/15954097/ce13e860-2e87-11e6-954b-72259a52f73a.PNG)

But as you can see, the project submission form isn't formatted yet.

![projects-page-3](https://cloud.githubusercontent.com/assets/5898368/15954114/02c7a5b0-2e88-11e6-9bc9-d24f376f9338.PNG)

Will we have this submission form in the final version of the website? The events page also has it, so I guess the more general question is, what do we plan to do with the submission forms?

**Comment by ChristianLapinig** [comment]
@TheBlueGamer55 Looks good, submit a PR and we'll be good
